name: 'Tag Page Generator for Jekyll Blogs'
description: 'Generates tag pages for Jekyll Blogs'
inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  source:
    description: 'Source of the tag JSON'
    required: true
  destination:
    description: 'Relative path to write tag pages'
    required: true
runs:
  using: 'node12'
  main: 'index.js'